In [10]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('train.csv')

In [3]:
df.sample(5, random_state=10)

id  Time_spent_Alone  ... Post_frequency  Personality
17833  17833               3.0  ...            6.0    Extrovert
10095  10095               3.0  ...            5.0    Extrovert
2141    2141               3.0  ...            5.0    Extrovert
13706  13706               3.0  ...            8.0    Extrovert
344      344               1.0  ...            NaN    Extrovert

[5 rows x 9 columns]

In [4]:
df['Personality'].value_counts()

Personality
Extrovert    13699
Introvert     4825
Name: count, dtype: int64

In [11]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer, KNNImputer


In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18524 entries, 0 to 18523
Data columns (total 9 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   id                         18524 non-null  int64  
 1   Time_spent_Alone           17334 non-null  float64
 2   Stage_fear                 16631 non-null  object 
 3   Social_event_attendance    17344 non-null  float64
 4   Going_outside              17058 non-null  float64
 5   Drained_after_socializing  17375 non-null  object 
 6   Friends_circle_size        17470 non-null  float64
 7   Post_frequency             17260 non-null  float64
 8   Personality                18524 non-null  object 
dtypes: float64(5), int64(1), object(3)
memory usage: 1.3+ MB


In [7]:
# df = df.dropna()

In [8]:
def boolToint(a):
    if (pd.isna(a) == False):    
        if(a.lower() == 'no'):
            return 0
        else:
            return 1

In [9]:
df['Stage_fear'] = df['Stage_fear'].apply(boolToint)

In [10]:
df['Drained_after_socializing'] = df['Drained_after_socializing'].apply(boolToint)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18524 entries, 0 to 18523
Data columns (total 9 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   id                         18524 non-null  int64  
 1   Time_spent_Alone           17334 non-null  float64
 2   Stage_fear                 16631 non-null  float64
 3   Social_event_attendance    17344 non-null  float64
 4   Going_outside              17058 non-null  float64
 5   Drained_after_socializing  17375 non-null  float64
 6   Friends_circle_size        17470 non-null  float64
 7   Post_frequency             17260 non-null  float64
 8   Personality                18524 non-null  object 
dtypes: float64(7), int64(1), object(1)
memory usage: 1.3+ MB


In [12]:
df.describe()

id  Time_spent_Alone  ...  Friends_circle_size  Post_frequency
count  18524.000000      17334.000000  ...         17470.000000    17260.000000
mean    9261.500000          3.137764  ...             7.996737        4.982097
std     5347.562529          3.003786  ...             4.223484        2.879139
min        0.000000          0.000000  ...             0.000000        0.000000
25%     4630.750000          1.000000  ...             5.000000        3.000000
50%     9261.500000          2.000000  ...             8.000000        5.000000
75%    13892.250000          4.000000  ...            12.000000        7.000000
max    18523.000000         11.000000  ...            15.000000       10.000000

[8 rows x 8 columns]

In [13]:
df.duplicated().value_counts()

False    18524
Name: count, dtype: int64

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18524 entries, 0 to 18523
Data columns (total 9 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   id                         18524 non-null  int64  
 1   Time_spent_Alone           17334 non-null  float64
 2   Stage_fear                 16631 non-null  float64
 3   Social_event_attendance    17344 non-null  float64
 4   Going_outside              17058 non-null  float64
 5   Drained_after_socializing  17375 non-null  float64
 6   Friends_circle_size        17470 non-null  float64
 7   Post_frequency             17260 non-null  float64
 8   Personality                18524 non-null  object 
dtypes: float64(7), int64(1), object(1)
memory usage: 1.3+ MB


In [15]:
df = df.drop(columns=['id'])

In [16]:
df.sample(5, random_state = 10)

Time_spent_Alone  Stage_fear  ...  Post_frequency  Personality
17833               3.0         0.0  ...             6.0    Extrovert
10095               3.0         0.0  ...             5.0    Extrovert
2141                3.0         NaN  ...             5.0    Extrovert
13706               3.0         0.0  ...             8.0    Extrovert
344                 1.0         0.0  ...             NaN    Extrovert

[5 rows x 8 columns]

In [12]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

In [18]:
scaler = MinMaxScaler()
df.iloc[:, 0:7] = scaler.fit_transform(df.iloc[: , 0:7])

In [19]:
df.sample(5, random_state= 10)

Time_spent_Alone  Stage_fear  ...  Post_frequency  Personality
17833          0.272727         0.0  ...             0.6    Extrovert
10095          0.272727         0.0  ...             0.5    Extrovert
2141           0.272727         NaN  ...             0.5    Extrovert
13706          0.272727         0.0  ...             0.8    Extrovert
344            0.090909         0.0  ...             NaN    Extrovert

[5 rows x 8 columns]

In [20]:
X= df.iloc[:, 0:7]
y= df.iloc[:, 7]

In [21]:
# imp = IterativeImputer(max_iter=10)
imp = KNNImputer(n_neighbors=5)
imp.set_output(transform = "pandas")
X = imp.fit_transform(X)

In [22]:
X.sample(5, random_state=10)

Time_spent_Alone  Stage_fear  ...  Friends_circle_size  Post_frequency
17833          0.272727         0.0  ...             0.666667            0.60
10095          0.272727         0.0  ...             0.733333            0.50
2141           0.272727         0.0  ...             0.733333            0.50
13706          0.272727         0.0  ...             0.666667            0.80
344            0.090909         0.0  ...             0.733333            0.44

[5 rows x 7 columns]

In [23]:
# df2.sample(5, random_state = 10)

In [24]:
y

0        Extrovert
1        Extrovert
2        Introvert
3        Extrovert
4        Extrovert
           ...    
18519    Extrovert
18520    Extrovert
18521    Introvert
18522    Introvert
18523    Extrovert
Name: Personality, Length: 18524, dtype: object

In [13]:
from sklearn.preprocessing import LabelBinarizer
lb = LabelBinarizer()

In [26]:
y = lb.fit_transform(y)

In [27]:
lb.classes_

array(['Extrovert', 'Introvert'], dtype='<U9')

In [28]:
y

array([[0],
       [0],
       [1],
       ...,
       [1],
       [1],
       [0]])

In [29]:
np.unique(y)

array([0, 1])

In [30]:
X_train, X_test, y_train, y_test= train_test_split(X, y, test_size=0.2, random_state=4)

In [31]:
X_train.shape

(14819, 7)

In [14]:
from sklearn.ensemble import RandomForestClassifier

In [84]:
rf = RandomForestClassifier(
    n_estimators=1000,
    max_depth=14,
    criterion='entropy',
    min_samples_split=10
)

In [ ]:
# from imblearn.ensemble import  BalancedRandomForestClassifier
# rf = BalancedRandomForestClassifier(
#     n_estimators=1000,
#     max_depth=14,
#     criterion='entropy',
#     min_samples_split=10,
#     random_state=5
#     )

In [85]:
rf.fit(X_train, y_train)

c:\Users\Shubham\tf-env\lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


RandomForestClassifier(criterion='entropy', max_depth=14, min_samples_split=10,
                       n_estimators=1000)

In [15]:
from sklearn.metrics import classification_report

In [87]:
pred = rf.predict(X_test)

In [88]:
print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       0.98      0.98      0.98      2751
           1       0.93      0.94      0.94       954

    accuracy                           0.97      3705
   macro avg       0.96      0.96      0.96      3705
weighted avg       0.97      0.97      0.97      3705



In [89]:
pred2 = rf.predict(X_train)
print(classification_report(y_train, pred2))

              precision    recall  f1-score   support

           0       0.98      0.98      0.98     10948
           1       0.95      0.94      0.94      3871

    accuracy                           0.97     14819
   macro avg       0.97      0.96      0.96     14819
weighted avg       0.97      0.97      0.97     14819



In [90]:
subm_df = pd.read_csv('test.csv')

In [91]:
subm_df.head()

id  Time_spent_Alone  ... Friends_circle_size  Post_frequency
0  18524               3.0  ...                 6.0             NaN
1  18525               NaN  ...                 5.0             1.0
2  18526               3.0  ...                15.0             9.0
3  18527               3.0  ...                 5.0             6.0
4  18528               9.0  ...                 1.0             1.0

[5 rows x 8 columns]

In [92]:
subm_df['Stage_fear'] = subm_df['Stage_fear'].apply(boolToint)

In [93]:
subm_df['Drained_after_socializing'] = subm_df['Drained_after_socializing'].apply(boolToint)

In [94]:
scaler = MinMaxScaler()
subm_df.iloc[:, 1:] = scaler.fit_transform(subm_df.iloc[: , 1:])

In [95]:
subm_df.head()

id  Time_spent_Alone  ...  Friends_circle_size  Post_frequency
0  18524          0.272727  ...             0.400000             NaN
1  18525               NaN  ...             0.333333             0.1
2  18526          0.272727  ...             1.000000             0.9
3  18527          0.272727  ...             0.333333             0.6
4  18528          0.818182  ...             0.066667             0.1

[5 rows x 8 columns]

In [96]:
subm_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6175 entries, 0 to 6174
Data columns (total 8 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   id                         6175 non-null   int64  
 1   Time_spent_Alone           5750 non-null   float64
 2   Stage_fear                 5577 non-null   float64
 3   Social_event_attendance    5778 non-null   float64
 4   Going_outside              5709 non-null   float64
 5   Drained_after_socializing  5743 non-null   float64
 6   Friends_circle_size        5825 non-null   float64
 7   Post_frequency             5767 non-null   float64
dtypes: float64(7), int64(1)
memory usage: 386.1 KB


In [97]:
subm_df2 = imp.fit_transform(subm_df.iloc[:,1:])

In [98]:
subm_df2

Time_spent_Alone  Stage_fear  ...  Friends_circle_size  Post_frequency
0             0.272727         0.0  ...             0.400000            0.78
1             0.636364         1.0  ...             0.333333            0.10
2             0.272727         0.0  ...             1.000000            0.90
3             0.272727         0.0  ...             0.333333            0.60
4             0.818182         1.0  ...             0.066667            0.10
...                ...         ...  ...                  ...             ...
6170          0.272727         0.0  ...             0.600000            0.60
6171          0.727273         1.0  ...             0.000000            0.00
6172          0.181818         0.0  ...             0.600000            0.70
6173          0.272727         0.0  ...             0.733333            0.90
6174          0.618182         1.0  ...             0.066667            0.00

[6175 rows x 7 columns]

In [99]:
pred_subm = rf.predict(subm_df2)

In [100]:
pred_subm

array([0, 1, 0, ..., 0, 0, 1])

In [101]:
pred_subm2 = lb.classes_[pred_subm]

In [102]:
pred_subm2

array(['Extrovert', 'Introvert', 'Extrovert', ..., 'Extrovert',
       'Extrovert', 'Introvert'], dtype='<U9')

In [103]:
subm_final_df = pd.DataFrame({
    'id': subm_df['id'],
    'Personality': pred_subm2
})

In [104]:
subm_final_df

id Personality
0     18524   Extrovert
1     18525   Introvert
2     18526   Extrovert
3     18527   Extrovert
4     18528   Introvert
...     ...         ...
6170  24694   Extrovert
6171  24695   Introvert
6172  24696   Extrovert
6173  24697   Extrovert
6174  24698   Introvert

[6175 rows x 2 columns]

In [105]:
subm_final_df = subm_final_df.set_index('id')

In [106]:
subm_final_df

Personality
id               
18524   Extrovert
18525   Introvert
18526   Extrovert
18527   Extrovert
18528   Introvert
...           ...
24694   Extrovert
24695   Introvert
24696   Extrovert
24697   Extrovert
24698   Introvert

[6175 rows x 1 columns]

In [107]:
subm_final_df.to_csv('final_submission6.csv')